name: daytte
description: It's a Dating App


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get:
  http:
  
  eva_icons_flutter: ^3.0.2
  intl:
  pin_code_fields:
  image_picker: ^0.8.4+1
  story_view: ^0.13.1
  swipe_cards: ^1.0.0 
  group_button: ^4.2.1
  flutter_svg: ^1.0.3
  flutter_custom_clippers: ^2.0.0
  dotted_border: ^2.0.0+1
  google_fonts: ^2.1.0
  dio: ^4.0.0
  get_storage: ^2.0.3
  getwidget: ^2.0.4
  geolocator: ^8.1.1
  lazy_load_scrollview: ^1.3.0
  connectivity_plus:
  share: ^2.0.4
  country_code_picker: ^2.0.2
  charts_flutter: ^0.12.0
  firebase_messaging: ^11.1.0
  firebase_core: ^1.10.0
  location: ^4.3.0
  socket_io_client: ^1.0.2
  emoji_picker_flutter: ^1.0.8
  #emoji_picker: ^0.1.0

  







dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/icon/
    - assets/images/



  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Regular.ttf
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Medium.ttf
          weight: 400
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Bold.ttf
          weight: 700

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli-Light.ttf
             

    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
    
    - family: ProximaNovaSoft
      fonts:
        - asset: assets/fonts/proxima-nova-soft.otf
    
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Medium.ttf   
    


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
